const DriverActionTypes = {
  GET_ALL_DRIVERS: "GET_ALL_DRIVERS",
  GET_ALL_DRIVERS_SUCCESS: "GET_ALL_DRIVERS_SUCCESS",
  GET_ALL_DRIVERS_FAILED: "GET_ALL_DRIVERS_FAILED",
  GET_ALL_DRIVERS_RESET: "GET_ALL_DRIVERS_RESET",
  GET_DRIVER_INFO: "GET_DRIVER_INFO",
  GET_DRIVER_INFO_SUCCESS: "GET_DRIVER_INFO_SUCCESS",
  GET_DRIVER_INFO_FAILED: "GET_ALL_DRIVERS_FAILED",
  GET_DRIVER_INFO_RESET: "GET_DRIVER_INFO_RESET",
  DRIVER_DATA_APPROVE: "DRIVER_DATA_APPROVE",
  DRIVER_DATA_APPROVE_SUCCESS: "DRIVER_DATA_APPROVE_SUCCESS",
  DRIVER_DATA_APPROVE_FAILED: "DRIVER_DATA_APPROVE_FAILED",
  DRIVER_DATA_APPROVE_RESET: "DRIVER_DATA_APPROVE_RESET",
  DRIVER_ACTIVE: "DRIVER_ACTIVE",
  DRIVER_ACTIVE_SUCCESS: "DRIVER_ACTIVE_SUCCESS",
  DRIVER_ACTIVE_FAILED: "DRIVER_ACTIVE_FAILED",
  DRIVER_ACTIVE_RESET: "DRIVER_ACTIVE_RESET",
};

export default DriverActionTypes;
