const DriverActionTypes = {
  GET_ALL_DRIVERS: "GET_ALL_DRIVERS",
  GET_ALL_DRIVERS_SUCCESS: "GET_ALL_DRIVERS_SUCCESS",
  GET_ALL_DRIVERS_FAILED: "GET_ALL_DRIVERS_FAILED",
  GET_ALL_DRIVERS_RESET: "GET_ALL_DRIVERS_RESET",
};

export default DriverActionTypes;
